create table inventoryconsumption(
menu_id int ,
sales_dough int,
sales_cheese int,
sales_sweet_potato int,
sales_sweet_potato_mousse int,
sales_potato int,
sales_sausage int,
sales_pepperoni int,
sales_corn int,
sales_tomato_sauce int,
sales_seafood_sauce int,
sales_hot_sauce int,
sales_mayonnaise int,
sales_coke int,
sales_cider int,
sales_pickle int,
sales_pimento int,
sales_onion int,
sales_mushroom int,
sales_pork int,
sales_beef int,
sales_parsley int,
sales_not_hq_tel varchar(20),
foreign key (menu_id) references menu(menu_id)
);